/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;


/**
 *
 * @author rpayan
 */
public class Lienzo extends javax.swing.JFrame {

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(antpos == null){antpos = evt.getPoint();}
        draw(evt.getPoint());
    }//GEN-LAST:event_formMouseClicked

    Point antpos;
    
    void draw (Point p)
    {
        int radio = 20;
        
        Graphics g = getGraphics();
        g.setColor(Color.BLUE);
        g.drawLine((int)p.getX()+radio/2, (int)p.getY()+radio/2, (int)antpos.getX()+radio/2, (int)antpos.getY()+radio/2);
        g.setColor(Color.red);
        g.fillOval((int)p.getX(), (int)p.getY(), radio, radio);
        //this.repaint();
        antpos = p;
    }
    
    void iWantToDie()
    {
        try 
        {
            URL url = new URL("https://www.eltiempo.com");
            BufferedReader bs = new BufferedReader(new InputStreamReader(url.openStream()));
            String txt;
            while ((txt = bs.readLine()) != null)
            {
                if (txt.startsWith("</")) 
                {
                    System.out.println(txt);
                }
                else if(txt.endsWith("/>"))
                {
                    System.out.println(txt.substring(0,txt.indexOf(">")+1)+" "+txt.substring(txt.lastIndexOf("<")));
                }
                else if (txt.startsWith("<")) 
                {
                    if (txt.contains(" ")) 
                    {
                        System.out.println(txt.substring(0,txt.indexOf(">")+1)+" "+txt.substring(txt.length()-1));
                    }
                    else
                    {
                        System.out.println(txt);
                    }
                    
                }
            }
            
        } 
        catch (Exception e) 
        {
            System.out.println("error en carga web");
            e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lienzo r= new Lienzo();
                r.setVisible(true);
                
                r.iWantToDie();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
